### ISSUE TITLE
Block List entries cannot be entered by pressing "Enter"

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/orion-design#1072]
I expected pressing enter would save the entry, but I need to click the checkbox
![image](https://user-images.githubusercontent.com/15331990/215236405-af4716a5-61d7-49d2-a43e-f5bdd413d291.png)

**Comment by zhen0** [comment]
Possibly also fixed by prefect design changes

**Comment by zhen0** [comment]
Checked and is fixed
